/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customcomponents;

import com.nezukoRent.database.ContractData;
import com.nezukoRent.managment.Login;
import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JDialog;

/**
 *
 * @author yassin
 */
public class HistoryItem extends javax.swing.JPanel {
    private ContractData contractData;
    /**
     * Creates new form HistoryItem
     */
    private Login LoginFrame; 
    
    public HistoryItem() {
        initComponents();
    }
    
   public HistoryItem(Login LoginFrame, ContractData contractData) {
    initComponents();
    this.LoginFrame = LoginFrame;
    this.contractData = contractData; 
     }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new RoundedButton("" , 30);

        setBackground(new java.awt.Color(217, 217, 217));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("user 123 a Louee appartement 21");

        jButton1.setBackground(new java.awt.Color(109, 170, 151));
        jButton1.setText("Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 494, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
       
  
     //   ShowContract(LoginFrame, contractData);
    
    }//GEN-LAST:event_jButton1ActionPerformed
   public void setText(ContractData contractData) {
    this.contractData = contractData; 
    StringBuilder label = new StringBuilder();
    label.append("user ").append(contractData.getIdClient()).append(" a Louee appartement ").append(contractData.getIdAppartement());
    jLabel1.setText(label.toString());
}
   
   public JButton getButton(){
       return this.jButton1;
   }

    
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
