/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customcomponents;

import com.nezukoRent.database.AppartementData;
import com.nezukoRent.managment.AddAppartement;
import com.nezukoRent.managment.Login;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author yassin
 */
public class PCards extends RoundJPanel {

    /**
     * Creates new form PCards
     */
    private boolean isListCard;
    public PCards(boolean isListCard ) {
        
        super(30);
        this.isListCard=isListCard;
        
        initComponents();
        initListCard();
     
    }
    
    
       public PCards(boolean isListCard , AppartementData appartement , Login loginFrame ) {
        
        super(30);
        this.isListCard=isListCard;
        
        initComponents();
        initListCard();
        addOnmouseClickedevent(appartement,loginFrame);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanel(30);
        jLabel1 =  new RoundedLabel("/icons/appr.jpg", 30,false , true);
        jPanel2 = new RoundedPanel(30);
        jPanel3 = new RoundedPanel(30);
        prixLabel = new javax.swing.JLabel();
        surfaceLabel = new javax.swing.JLabel();
        chambreLabel = new javax.swing.JLabel();
        villeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(228, 211, 231));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 214, 237));

        jLabel1.setBackground(new java.awt.Color(255, 214, 218));
        jLabel1.setIconTextGap(0);

        jPanel2.setBackground(new java.awt.Color(255, 214, 237));

        jPanel3.setBackground(new java.awt.Color(255, 214, 237));

        prixLabel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        prixLabel.setText("Prix:300DH");
        prixLabel.setIconTextGap(1);

        surfaceLabel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        surfaceLabel.setText("Surface:100m²");

        chambreLabel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        chambreLabel.setText("chambre:3");
        chambreLabel.setIconTextGap(1);

        villeLabel.setBackground(new java.awt.Color(242, 208, 234));
        villeLabel.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        villeLabel.setText("Ville: Agadir");
        villeLabel.setIconTextGap(1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prixLabel)
                    .addComponent(villeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surfaceLabel)
                    .addComponent(chambreLabel))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixLabel)
                    .addComponent(surfaceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chambreLabel)
                    .addComponent(villeLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    public void initListCard(){
                if(this.isListCard){
                  PcardFooter pc = new PcardFooter();
                  jPanel2.setLayout(new BorderLayout()); 
                  PcardFooter pfooter=new PcardFooter();
                  jPanel2.remove(jPanel3);
                  jPanel2.add(pc, BorderLayout.SOUTH);
                  jPanel2.revalidate();
                  jPanel2.repaint();
        }
                
    }
    
    public void addOnmouseClickedevent(AppartementData appartement,Login loginFrame){
        this.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        // Handle the mouse click event here
                AddAppartement addApcard = new AddAppartement(loginFrame , appartement);
                  loginFrame.addPanel(addApcard, "editApp");
                   loginFrame.showPanel("editApp");

    }
});
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel chambreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel prixLabel;
    public javax.swing.JLabel surfaceLabel;
    public javax.swing.JLabel villeLabel;
    // End of variables declaration//GEN-END:variables
}
