/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nezukoRent.managment;
import com.nezukoRent.database.AppartementData;
import com.nezukoRent.database.AppartementTableHandler;
import com.nezukoRent.database.VilleData;
import com.nezukoRent.database.VilleTableHandler;
import com.nezukoRent.database.QuartierData;
import com.nezukoRent.database.QuartierTableHandler;
import ui.customcomponents.RoundedTextField;
import ui.customcomponents.RoundedLabel;
import ui.customcomponents.RoundedButton;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author yassin
 */
public class AddAppartement extends javax.swing.JPanel {

    /**
     * Creates new form AddAppartement
     */
    private Login LoginFrame;
    private int SelectedVilleId;
    private AppartementData appartement;
    public AddAppartement(Login LoginFrame) {
        this.LoginFrame=LoginFrame;
        initComponents();
        
        populateVillesComboBox();
       
    }
    
      public AddAppartement(Login LoginFrame , AppartementData appartement) {
        this.LoginFrame=LoginFrame;
        
        this.appartement=appartement;
        initComponents();
       
        populateVillesComboBox();
        initInfo(appartement);
        addDeleteButton(jPanel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descreptionText = new javax.swing.JTextArea();
        villeCombobox = new javax.swing.JComboBox<>();
        appartementTypeCombobox = new javax.swing.JComboBox<>();
        quartierCombobox = new javax.swing.JComboBox<>();
        chambreCombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        isMeublee = new javax.swing.JCheckBox();
        isDisponible = new javax.swing.JCheckBox();
        prixInput = new RoundedTextField(30);
        surfaceInput = new RoundedTextField(30);
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new RoundedLabel("/icons/image.png", 30 , true,true);
        jLabel9 = new RoundedLabel("/icons/image.png", 30,true , true);
        jLabel12 = new RoundedLabel("/icons/image.png", 30 , true , true);
        jLabel13 = new RoundedLabel("/icons/image.png", 30 , true , true);
        jLabel14 = new RoundedLabel("/icons/image.png", 30 , true , true);
        jLabel15 = new RoundedLabel("/home/yassin/Desktop/cours/s6/mobile/image.png", 30,true , false);
        jLabel11 = new RoundedLabel("/home/yassin/Desktop/cours/s6/mobile/ADD1.png", 30 , true , false);
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new RoundedButton("" , 30);
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 241, 244));
        setPreferredSize(new java.awt.Dimension(984, 406));

        jPanel2.setBackground(new java.awt.Color(237, 241, 244));
        jPanel2.setPreferredSize(new java.awt.Dimension(516, 70));

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton1.setText("Appartements");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(192, 192, 192));
        jButton4.setText("Clients");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(192, 192, 192));
        jButton5.setText("Analytics");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_keyboard_arrow_right_24px.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addGap(52, 52, 52)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setBorder(BorderFactory.createEmptyBorder());

        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton4.setBorder(BorderFactory.createEmptyBorder());
        jButton5.setBorder(BorderFactory.createEmptyBorder());
        jButton1.setBorder(BorderFactory.createEmptyBorder());

        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/setting_1.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(237, 241, 244));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel1.setText("Descreption");

        descreptionText.setColumns(20);
        descreptionText.setRows(5);
        jScrollPane1.setViewportView(descreptionText);

        villeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        villeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeComboboxActionPerformed(evt);
            }
        });

        appartementTypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quartierCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chambreCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel2.setText("Ville");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel3.setText("Surface");

        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel4.setText("Prix(DH)");

        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel5.setText("Type");

        jLabel6.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel6.setText("Quartier");

        jLabel7.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        jLabel7.setText("Chambre");

        isMeublee.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        isMeublee.setText("meublée");
        isMeublee.setOpaque(false);
        isMeublee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isMeubleeActionPerformed(evt);
            }
        });

        isDisponible.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        isDisponible.setOpaque(false);
        isDisponible.setText("Disponible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(isMeublee)
                            .addComponent(prixInput)
                            .addComponent(appartementTypeCombobox, 0, 196, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(isDisponible)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(chambreCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(216, 216, 216)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(0, 125, Short.MAX_VALUE))
                            .addComponent(surfaceInput)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(villeCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91)
                        .addComponent(quartierCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quartierCombobox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(villeCombobox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surfaceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chambreCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appartementTypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isMeublee)
                    .addComponent(isDisponible))
                .addGap(35, 35, 35))
        );

        jPanel3.setBorder(new EmptyBorder(25, 95, 15, 95)); // Top, left, bottom, right padding
        jPanel3.setLayout(new BorderLayout());
        jPanel3.setBackground(new java.awt.Color(237, 241, 244));
        jPanel3.setLayout(new java.awt.GridLayout(3, 3, 12, 12));

        jLabel8.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel8);

        jLabel9.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel9);

        jLabel12.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel12);

        jLabel13.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel13);

        jLabel14.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel14);

        jLabel15.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel15);

        jLabel11.setBackground(new java.awt.Color(153, 153, 0));
        jPanel3.add(jLabel11);

        jPanel4.setBackground(new java.awt.Color(237, 241, 244));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton3.setBackground(new java.awt.Color(109, 145, 129));
        jButton3.setFont(new java.awt.Font("Likhan", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ajouter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 370, 25, 393);
        jPanel4.add(jButton3, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Gérer Quartiers");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Gérer Villes");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBorder(BorderFactory.createEmptyBorder());
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Appartements.ShowSettings(LoginFrame);
        //scrollPane.setViewportView(jPanel4);

        //scrollPane.revalidate();  // Make sure the scroll pane updates
        //scrollPane.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void isMeubleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isMeubleeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isMeubleeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        double prix =   Double.valueOf(prixInput.getText());
        double surface =   Double.valueOf(surfaceInput.getText());
        int villeId =getVillId(villeCombobox.getSelectedItem().toString());
        String quartier = quartierCombobox.getSelectedItem().toString();
        int idQuartier = QuartierTableHandler.getQuartierId(quartier , villeId);
        Boolean ismeublee = isMeublee.isSelected();
        Boolean disponible = isDisponible.isSelected();
        String type=appartementTypeCombobox.getSelectedItem().toString();
        int numChambres = Integer.valueOf(chambreCombobox.getSelectedItem().toString());
        //addAppartement( type,  surface,  chambres,  disponibilite,boolean meublee, double prix, int ville_id, int quartier_id)
         System.out.println("quartier id *********: "+ idQuartier + " **** ville id  : "+ villeId);
        AppartementTableHandler.addAppartement(type, surface, numChambres, disponible,ismeublee, prix, villeId, idQuartier);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void initInfo(AppartementData appartement){
        prixInput.setText(String.valueOf(appartement.getPrix()));
        surfaceInput.setText(String.valueOf(appartement.getSurface()));
        
        String currentQT=QuartierTableHandler.getQuartierId(appartement.getQuartierId());
        String currentVL=VilleTableHandler.getVilleNameById(appartement.getVilleId());
        System.out.println("quartier id :  : "+currentQT);
        villeCombobox.setSelectedItem(currentVL);
         quartierCombobox.setSelectedItem(currentQT);
         appartementTypeCombobox.setSelectedItem(appartement.getType());
         chambreCombobox.setSelectedItem(String.valueOf(appartement.getChambres()));
         isMeublee.setSelected(true);
         isDisponible.setSelected(true);

    
         
    //prixInput.setText("");
    }
    
    private void populateVillesComboBox() {
    // Retrieve the list of villes
    List<VilleData> villes = VilleTableHandler.getAllVilles();

    // Create a DefaultComboBoxModel and populate it with the names of the villes
    DefaultComboBoxModel<String> villeComboBoxModel = new DefaultComboBoxModel<>();
    for (VilleData ville : villes) {
        villeComboBoxModel.addElement(ville.getName());
    }

    // Set the populated DefaultComboBoxModel as the model for your JComboBox
    villeCombobox.setModel(villeComboBoxModel);
     String selectedVilleName = (String) villeCombobox.getSelectedItem();
        
        
        populateQuartiersComboBox(getVillId(selectedVilleName));
}
        private void populateQuartiersComboBox(int villeId) {
    // Retrieve the list of villes
    List<QuartierData> villes = QuartierTableHandler.getQuartiersByVille(villeId);

    DefaultComboBoxModel<String> QuartierComboBoxModel = new DefaultComboBoxModel<>();
    for (QuartierData ville : villes) {
        QuartierComboBoxModel.addElement(ville.getName());
    }

    // Set the populated DefaultComboBoxModel as the model for your JComboBox
    quartierCombobox.setModel(QuartierComboBoxModel);
}
    
    
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          Appartements.getAPP(false, LoginFrame);
  
  
   
                   this.LoginFrame.showPanel("Home");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        
     
       Quartier quartier = new Quartier();
     JDialog overlayDialog = new JDialog(this.LoginFrame, "Gérer Quartiers", Dialog.ModalityType.APPLICATION_MODAL);
     overlayDialog.setContentPane(quartier);
     overlayDialog.setSize(400, 450);
     overlayDialog.setResizable(false);
     overlayDialog.setLocationRelativeTo(this.LoginFrame);
     overlayDialog.setVisible(true);

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
            Ville ville = new Ville();
     JDialog overlayDialog = new JDialog(this.LoginFrame, "Gérer Villes", Dialog.ModalityType.APPLICATION_MODAL);
     overlayDialog.setContentPane(ville);
     overlayDialog.setSize(400, 450);
     overlayDialog.setResizable(false);
     overlayDialog.setLocationRelativeTo(this.LoginFrame);
     overlayDialog.setVisible(true);
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void villeComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeComboboxActionPerformed
        // TODO add your handling code here:
       // populateQuartiersComboBox(jComboBox1.getSelectedItem().toString());
        
         String selectedVilleName = (String) villeCombobox.getSelectedItem();
        
        
        populateQuartiersComboBox(getVillId(selectedVilleName));
        
    }//GEN-LAST:event_villeComboboxActionPerformed

    public   int getVillId(String name){
         String selectedVilleName = (String) villeCombobox.getSelectedItem();
          VilleData selectedVille = null;
          List<VilleData> villes = VilleTableHandler.getAllVilles();
        for (VilleData ville : villes) {
            if (ville.getName().equals(selectedVilleName)) {
                selectedVille = ville;
                break;
            }
        }
        return selectedVille.getId() ;
    }
    public  void addDeleteButton(JPanel panel) {
 
        JButton ajouterButton = jButton3;
        Dimension preferredSize = new Dimension(150, 40); // Larger size

        JButton deleteButton = new RoundedButton("Delete",30);
        deleteButton.setBackground(new Color(193, 12, 25));
        deleteButton.setFont(new Font("Likhan", Font.BOLD, 18));
        deleteButton.setForeground(Color.WHITE);
        deleteButton.setPreferredSize(preferredSize);

        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteApp();
            }
        });

        panel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(0, 10, 0, 0); 
        gbc.anchor = GridBagConstraints.CENTER;

        ajouterButton.setPreferredSize(preferredSize);
        gbc.gridx = 0;
        panel.add(ajouterButton, gbc);

        gbc.gridx = 1;
        panel.add(deleteButton, gbc);
    }

    public  void deleteApp() {
       
         if(JOptionPane.showConfirmDialog(null, "Are you sure you want to clear table Quartier?", "Confirmation", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
         
            if( AppartementTableHandler.deleteAppartement(appartement.getId())){
                 JOptionPane.showMessageDialog(null, "Appartement deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE); 
                this.LoginFrame.showPanel("Home");
             
        Appartements.getAPP(false, LoginFrame);
            }else{
                   JOptionPane.showMessageDialog(null, "Failed detelke Appartement.", "Error", JOptionPane.ERROR_MESSAGE);
            }
             
             System.out.println("appid : " + appartement.getId());
             
         
         }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> appartementTypeCombobox;
    private javax.swing.JComboBox<String> chambreCombobox;
    private javax.swing.JTextArea descreptionText;
    private javax.swing.JCheckBox isDisponible;
    private javax.swing.JCheckBox isMeublee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prixInput;
    private javax.swing.JComboBox<String> quartierCombobox;
    private javax.swing.JTextField surfaceInput;
    private javax.swing.JComboBox<String> villeCombobox;
    // End of variables declaration//GEN-END:variables
}
